OnionUI/Onion

- README.md
Revamped the [README](https://github.com/OnionUI/Onion/tree/readme-revamp) with some visual tweaks and clearer wording in some places.
> Readme revamp

- src/packageManager/packageManager.c
* fixes #91 (exclude Mac's dot items)
* fix compiler warnings
> pacman updates

- src/randomGamePicker/randomGamePicker.c
- static/build/App/romscripts/Random game.sh
This PR add a new option to game menu where players can choose a random game to play.
> Including new Game Menu option "Random Game"

- src/infoPanel/appstate.h
- src/infoPanel/imagesCache.c
- src/infoPanel/imagesCache.h
- src/infoPanel/infoPanel.c
- test/test_infoPanel.cpp
- added theme-aware drawing
- fixed warnings
> fixed #113

- static/build/miyoo/app/lang/pl.lang
> Small update to Polish translation 

- static/build/.tmp_update/script/easynetplay/netplay_client.sh
- static/build/.tmp_update/script/easynetplay/netplay_server.sh
- static/build/.tmp_update/script/easynetplay/pokemon_client.sh
- static/build/.tmp_update/script/easynetplay/pokemon_server.sh
> CHORE: Align logging in EN/Pokémon Scripts after PRs

- website/docs/01-getting-started/02-features/02-network-features-mmp/03-ssh-sftp.md
Add details for to the SSH page here:
https://onionui.github.io/docs/network/ssh
To describe a working fix for connections via some dists/SSH client versions.
> DOCS: Add fix for some users to SSH page

- static/build/.tmp_update/script/network/update_networking.sh
Fix 2 issues in update_networking.sh causing:
unknown operand 
illegal number
> FIX: "unknown operand" error caused by update_networking.sh

- static/build/.tmp_update/script/network/update_networking.sh
China or some country can not use google. can not ping google for checking network. Just use worldtimeapi.org is OK.
> FIX: fix network check

- website/docs/07-apps/01-included-in-onion/retroarch.md
> chore: typo correction

- Makefile
- src/common/system/display.h
FIX: don't close a file that has not been opened
also bump RA_SUBVERSON
> FIX: don't close a file that has not been opened

- static/configs/Saves/CurrentProfile/saves/PICO-8/.lexaloffle/pico-8/config.txt
- static/packages/RApp/PICO-8 (PICO-8 standalone)/RApp/PICO-8/launch.sh
- Fix little stuttering on [bench test](https://dl.dropbox.com/scl/fi/x3kgfpg18tum8b0zv26em/perf2.p8?rlkey=6xbyakr1ml95urt4t9lxxfcic&dl=0)
- Fix bin folder presence
- Fix config.txt file creation when it's not present
> Pico-8 Wrapper configuration improvement

- static/build/.tmp_update/script/screen_recorder.sh
Before:
https://github.com/OnionUI/Onion/assets/47260768/2aedfc7f-22b3-4c7d-b294-c9d1b6bfb871
After:
https://github.com/OnionUI/Onion/assets/47260768/c9ca0604-3fbb-4947-905e-885cf56c1e4e
> Minor screen recorder config changes

- website/docs/08-guides/02-theme-design/index.md
> Update Theme Design

- static/build/.tmp_update/script/network/update_networking.sh
Some things not working when building a fresh main & fixing a rando blackscreen issue when disabling wifi & opening search...
> Net service store simplify & bugfix 

- website/docs/07-apps/02-community-apps/index.mdx
> Adds Lynx web browser

- static/build/.tmp_update/runtime.sh
> Fix resolution on MM with newer firmware

- website/docs/07-apps/02-community-apps/storii.md
Add storii, a children friendly mp3 player app for the Miyoo Mini (+) in the community app section.
> Add storii.md

- website/docs/01-features/index.md
- website/docs/03-faq/index.mdx
- website/docs/04-emulators/02-consoles/35-snk-neo-geo.md
- website/docs/04-emulators/05-miscellaneous/13-scummvm.md
- website/docs/06-multiplayer-netplay/03-easynetplay-pokemon.md
- website/docs/07-apps/01-included-in-onion/search.md
- website/docs/07-apps/03-network-features/05-telnet.md
Cleaned up some typos across the website docs.
> Website documentation typos

- website/docs/02-installation/index.mdx
Reuploaded fw to my Gdrive
Fixes #1671
> Fix invalid firmware download link

- website/docs/03-faq/index.mdx
* Re-word overclocking instructions
* Clarify Retroarch root folder location
* Remove preceding spaces before colons
> Improve overlock FAQ content

- website/docs/01-features/index.md
> Update index.md grammar

- website/docs/02-installation/01-fresh-install.mdx
* Linux "cp" command correction
* Remove recommendation of using stock BIOS
Closes #1774
> Improve fresh install documentation
