OnionUI/Onion

- src/gameSwitcher/gameSwitcher.c
- src/packageManager/packageManager.c
- gameSwitcher go back in simple buffering
- pacman doesn't select the next item automatically after a modification
> gameSwitcher go back in simple buffering

- static/build/miyoo/app/lang/nl.lang.short
This translates "No thumbnail" to "Geen thumbnail"
> fix(nl-lang-short): translate "no thumbnail" to dutch

- static/packages/RApp/Nintendo - GB (TGB Dual)/RApp/TGB_Dual/config.json
- static/packages/RApp/Nintendo - GBC (TGB Dual)/RApp/TGB_Dual_gbc/config.json
- static/packages/RApp/Nintendo - GBC (TGB Dual)/RApp/TGB_Dual_gbc/launch.sh
Hi, i'm new and would like to contribute to this amazing Onion OS!
I found out with the new 4.2 beta we have the TGB Dual in Expert section of Package Manager but it only load `.gb` file
Excited enough to try out `.gbc` games with multiplayer, thus I manually duplicate another folder that points to GBC roms folder too, would it be feasible?
> Add TGB Dual GBC into Package Manager

- .github/workflows/test.yml
- Makefile
Attempting small implementation for #85, highly looking forward to any feedback or requested changes.
- Added `static-analysis` make target
- Added static analysis step to `test.yml` GitHub pipeline. The same will not fail the build currently, this can be reassessed once the static code report is further reviewed
> Add static code analysis tool to the build process

- Makefile
- static/dist/miyoo/app/.tmp_update/install.sh
- 7z is used instead of unzip during Onion installation
- No more failure during extract with big onion.pak
> Replacing unzip with 7z in installer

- static/build/.tmp_update/script/update_networking.sh
This was caused by NTP not being backgrounded - it was called in by update_networking.sh to update the time but in the wrong place, so when the state of a toggle was changed ntpdate ran but in the FG instead of BG, when the process dies the UI frees up.
- Moved ntp into the check_ntpstate func, it runs often (when network state is changed in tweaks) but this will ensure time is kept closely in line with NTP, it's a self terminating process so won't hang around long.
- Backgrounded 2 calls of ntp
> Fix: The long delay in/out of Tweaks when network services changed

- src/installUI/installUI.c
move imageCache_getItem out of main loop so it doesn't get called every 15 msec
adresses #929
> Improve memory leak in installUI

- static/dist/.tmp_update/runtime.sh
- static/dist/.tmp_update/updater
- static/dist/miyoo/app/.tmp_update/install.sh
- Before 20230506 firmwares runs .tmp_update/updater script , after .tmp_update/runtime.sh. So we put the logic in runtime.sh and proxy it in updater
- Do not count files in zip file anymore.
- Reboot before exiting the script, l584(to avoid that main script continue his job and suppress .tmp_update folder)
> Fix install bugs

- src/common/system/settings.h
- src/keymon/keymon.c
- src/tweaks/actions.h
- src/tweaks/menus.h
**What it does:**
Adds a setting "Power single press" with the values "Standby (default)" and "Shutdown" in "Button Shortcuts" 
Setting this to "Shutdown" will make it so the device shuts down at the single press of the power button instead of going to standby.
This disables the standby functionality.
**To test:**
- Go to Apps/Tweaks/Button shortcuts
- Set "Power single press" to "Shutdown"
- Exit out of tweaks to the home menu
- Press and do not hold the power button 
- _The device shuts down_
- Go to Apps/Tweaks/Button shortcuts
- Set "Power single press" to "Standby"
- Exit out of tweaks to the home menu
- Press and do not hold the power button 
- _The device goes into standby_
> Add toggle for disabling standby (instant shutdown)

- static/packages/Emu/Commodore - C64 (VICE x64)/Emu/COMMODORE/config.json
Add extlist to COMMODORE config.json. Matches the supported extensions documented in the wiki.
> Update COMMODORE config.json: add extlist

- src/axp/Makefile
- src/batmon/Makefile
- src/bootScreen/Makefile
- src/chargingState/Makefile
- src/common/config.mk
- src/easter/Makefile
- src/jpg2png/Makefile
- src/keymon/Makefile
- src/packageManager/Makefile
- src/playActivity/Makefile
- src/playActivityUI/Makefile
- src/pngScale/Makefile
- src/randomGamePicker/Makefile
- src/themeSwitcher/Makefile
Some binaries still had "-s" in their Makefiles which prevented them from being built with debug symbols. For non-debug builds the symbols are stripped in a seperate step, so this is unnecessary.
Also raised debug level to -g3 to allow for better debugging.
> CHORE: Remove leftover "-s" flags and raise debug level

- Makefile
- static/dist/miyoo/app/.tmp_update/install.sh
As discussed, replace zip with 7z in build process.
Change installation message to "Preparing folders"... while stuck at 0%
Allows for reproducible .pak files.
Also reduces release file size by ~20% (release.zip ~500MB to 400MB), install time increases by about 10 seconds.
Tested on SanDisk ultra 32GB from press of power button until Quick Guide shows up:
dev-41caa40: 2 minutes 59 seconds
with this PR:   3 minutes 10 seconds
I've tested fresh install and update on MM+
> CHORE:Replace zip with 7z in build process

- static/build/.tmp_update/script/network/update_networking.sh
In situations where wifi is lost we can get stuck in the ntpWait loop (can happen randomly as `rm /tmp/ntp_run_once` wouldn't have executed so the file will still exist)
- Added a 20 second timeout.
- Check return value of ntpdate and write log entry if it fails for debug
- Move "rm /tmp/ntp_run_once" out of the loop incase we never make it to the get_time function call, otherwise we get a random long delay exiting tweaks (or completely stuck if the loop won't break)
> FIX: Adds exit condition to NTPwait loop

- src/tweaks/menus.h
- src/tweaks/reset.h
- static/build/.tmp_update/res/wpa_supplicant.reset
- static/dist/miyoo/app/.tmp_update/install.sh
#976 introduced a bug, it failed to extract the config files on installation, because they are packed in 7z (LZMA) format and unpacked with unzip.
Fixed by replacing unzip with 7z
"Reset MainUI settings" was not working because, it tried to extract system.json from config.pak, which isn't in there anymore since at least 4.1.4. Copy it from /mnt/SDCARD/.tmp_update/res/ instead. Choose the right one depending on DEVICE_ID.
Replace unzip with 7z in all Tweaks/Reset actions that require unpacking. This also did not work anymore because #976 changed the format of config.pak from zip to 7z (LZMA).
Testing procedure:
> FIX: Replace unzip with 7z for configs.pak and Tweaks

- static/build/.tmp_update/script/easynetplay/netplay_client.sh
- static/build/.tmp_update/script/easynetplay/netplay_server.sh
- static/build/.tmp_update/script/easynetplay/pokemon_client.sh
- static/build/.tmp_update/script/easynetplay/pokemon_server.sh
Added stop notification/checks on both host and client to catch problems at any step.
Check whether the rom disappears after the client hits the join button (this should never happen)
File checks reworked
Logging reworked
More logging added
Remove unnecessary exports
Add notification to Pokemon Host/Client scripts to stop before the confirm panel if critical files are not synced
General refactors (duplicate actions become functions)
Added sleeps to allow for more time reading infopanels
Added sleep to allow hostapd to work before (in rare cases) reporting it has failed and is retrying (but still succeeding)
> REFACTOR: Changes to Easy Netplay & Pokemon trading GLO scripts

- src/tweaks/menus.h
- src/tweaks/tools.h
- src/tweaks/tools_defs.h
- static/build/.tmp_update/script/miyoogamelist_gen.sh
Add a script/tool that generate `miyoogamelist.xml` for all systems (except Arcades).
I chose to exclude arcade titles because they have their own gamelist already.
In the process, it removes additional info from the name of the game, assuming the roms are names according to [No-Intro Naming Convention](https://wiki.no-intro.org/index.php?title=Naming_Convention).
Also, the script will backup existing `miyoogamelist.xml` files to  `miyoogamelist.xml.bak` in case the user add one already and avoid losing it.
~~There is room for improvement, for instance replacing " - " by ": " in names or moving back articles to the beginning o the name (ie: "Legend of Zelda, The" -> "The Legend of Zelda")~~ 
Edit: Articles (The, A, An) are moved to the start of the name (according to naming convention) …
> FEAT: Added tool to automatically generate miyoogamelists with clean names

- Makefile
- src/keymon/menuButtonAction.h
- Overclocking is now preserved when returning from standby
- Overclocking per core is now possible (put a `cpuclock.txt` file inside the core config directory)
- BONUS: play activity is paused while in RA menu
> FEAT: Better OC support

- src/playActivity/cacheDB.h
- src/playActivity/playActivityDB.h
Problem:
- When launching a game from GameSwitcher that's not yet cached, box art is not added
- When launching the game again with cache, box art is not updated
Changes:
- Update rom info from cache on play activity start
> FIX: Update rom info on play activity start

- static/build/.tmp_update/script/miyoogamelist_gen.sh
When testing further name cleaning I found out 2 issues:
- On no-match `sed` return the string untouched, causing duplicate when no article is present in some cases, fixed by `-n` option combined with `/p` command
- The brackets regex was too agressive, it matched from the opening bracket to the **last** closing one, not the **next**
> FIX: miyoogamelist_gen fix sed behavior on no-match & aggressive bracket regex

- static/build/.tmp_update/script/migration/00013_fix_hostapd_config.sh
Minor change.
PR to add a migration script to add the missing line to the top of the .conf file.
Fixes "Hostapd hook failing" loop when trying to setup an easy netplay session for pokemon
Hostapd ctrl_interface was added in ENP PR to the conf, the conf won't get updated without a full install.
> FIX: Add migration script for hostapd.conf fix

- static/build/.tmp_update/runtime.sh
Very minor change.
The logging entries changed when the logging method was changed to a sourced script that uses the scripts name.
@schmurtzm should `scrap.log` also be added to this or are you keeping it over reboots??
> FIX: Re-add missing logfiles from runtime.sh clear_logs function.

- website/docs/01-getting-started/01-installation/01-fresh-install.mdx
- website/docs/01-getting-started/01-installation/02-upgrading.mdx
Added instructions for Chrome OS. Unfortunately, Chrome OS doesn't support overwriting or merging files when copying/moving them into a location with files with the same names, making the upgrade process much more difficult than it should be. I resorted to recommending doing a backup and performing a clean install instead.
> DOCS: Added installation and upgrade instructions for Chrome OS

- static/build/.tmp_update/runtime.sh
The display init procedure looks at `/appconfigs/system.json` for the display values. This file was moved to `/mnt/SDCARD/system.json` in 4.2.1 - but the symlink from appconfigs was made *after* display init.
- Moved the symlink creation above the display init in the runtime init procedure
> FIX: Display settings not applying in 4.2.1

- static/build/.tmp_update/script/diagnostics/util_exporter.sh
Fixes the location of the reported logfile dump
(util_exporter) 2023-09-25 13:12:17: Exported to: .tmp_update/log_export.7z
to
(util_exporter) 2023-09-25 13:09:17: Exported to: /mnt/SDCARD/log_export.7z
> FIX: exporter log entry location

- src/tweaks/appstate.h
- src/tweaks/menus.h
- src/tweaks/tools.h
- src/tweaks/tools_defs.h
- static/build/.tmp_update/script/cue_gen.sh
- static/build/.tmp_update/script/m3u_gen.sh
- static/build/RetroArch/.retroarch/cores/mednafen_pcfx_libretro.info
Create playlists automatically from multidisk roms New script m3u_gen.sh (easy to adapt to GLO if necessary) 
Available from `Tweaks` -> `Tools` section.
Additional folders added to cue generator.
By default the script is systematically applied to `PS, SEGACD, NEOCD, PCE, PCFX, AMIGA` rom folders.
The supported multidisc file names are numerous (not key sensitive and support "disc" or "disk"), for example : 
`MyGame (Disc 1).chd` or `MyGame (disc 1).chd` or `MyGame (DISC 1).chd` or `MyGame (Disk 1).chd`
`MyGame (USA) (Disc 1).bin` + `MyGame (USA) (Disc 1).cue`
`MyGame (USA) (Disc 1) (Rev 1).chd`
`MyGame (Disc 1 of .2).chd`
...
> FEAT: multidisc playlist (.m3u) generator

- src/tweaks/menus.h
- src/tweaks/tools.h
- src/tweaks/tools_defs.h
- static/build/.tmp_update/script/app_sorter.sh
- Tested on MM+ FW 0628, MM 1027, MM 0611
- Tested with Sandisk Ultra cards
- Will add 2 tools to the Tweaks -> Tools menu
> FEAT: App list sorting tool (asc/desc A-Z)

- static/packages/App/Guest Mode/App/Guest_Mode/launch.sh
The current theme is stored in 
/mnt/SDCARD/Saves/CurrentProfile/theme/currentTheme
> FEAT: Integrate theme, favorites, and recent list functionalities to be profile-specific.

- static/build/.tmp_update/runtime.sh
This is for the 5 people who are crazy and/or skilled enough to do the RTC mod.
Normally, Onion saves the system time at shutdown and restores it on bootup. This disables the restore part.
Since it would be a useless/confusing option for 99.9% of users it has to be enabled by manually creating the file 
`SD:/.tmp_update/config/.noTimeRestore`
Motivated to finally include this by #1334
> FEAT: Add option to disable time restore

- src/common/system/settings.h
- static/build/.tmp_update/runtime.sh
Moved bgm_mute setting out of system.json into $sysdir/config/
Background:
Whenever MainUI writes to system.json it clears out the whole file and rewrites it. This deletes the additional bgm_vol key out of system.json.
For example, if you were to mute the background music, then change the menu sound in MainUI settings, the bgm_vol key would be deleted from system.json and the background music would play.
> FIX: bgm_mute setting gets deleted by MainUI

- static/build/.tmp_update/runtime.sh
"Hooks" so third party apps can add it's own scripts on boot and power off
> Startup and checkoff scripts

- static/packages/App/Gallery (Screenshot viewer)/App/Screenshots_Viewer/launch.sh
Exit from gallery when existing images will return code 255, that cause a error hint, but do not need it actually.
> FIX: fix hint no screenshoot images after back from first image

- .gitattributes
- .github/create_fullres_files.sh
- Makefile
- static/build/.tmp_update/runtime.sh
- static/configs/.tmp_update/config/res_exceptions
Replace the central res_exceptions file, which had a list of strings run against cmd_to_run.sh, with a per-program approach.
If a game/app wants to launch in 560p, it needs a file `full_resolution` next to it's launch.sh. 
This has multiple benefits, for example
- No need to iterate over a growing file on each game/app launch
- a user can easily remove or add the file if needed
A drawback would be that this is more of a whitelist approach, so for every system/app/game which can run in 560p, the according file must be created.
This is done at build time by the newly added script [create_fullres_files.sh](https://github.com/OnionUI/Onion/compare/replace-blacklist-with-something-better#diff-bca2ea91900785aa120dd3ba50be7f10f914e7b43acd0f6600b6a6a66df2fec6)
> FIX: Replace global resolution blacklist with a per-game/app whitelist file

- .github/create_fullres_files.sh
- Makefile
- static/build/.tmp_update/runtime.sh
- static/build/.tmp_update/script/change_resolution.sh
**RetroArch changes the resolution now itself**
**Improve 560p whitelist to support ports**
Ports using RetroArch are automatically whitelisted
Other ports must include `FullResolution=1` to their .port script
**Fix 560p not working with GLO core overrides**
**fix 560p not working when RetroArch is the startup app**
> FIX: 560p improvements

- src/batmon/batmon.c
- src/batmon/batmon.h
- src/common/theme/resources.h
This fix disabled the low battery warning when MainUI and other apps with a battery displayed are running
> Fixed low battery warning overlapping other battery icons

- src/common/utils/file.c
Replace stat() with stat64() which works the same but is compatible with files larger than 2GB
> The fstat64(), lstat64(), and stat64() functions are identical to the fstat(), lstat() and stat() functions except that they take a pointer to struct stat64 instead of struct stat. This permits applications to determine the size of a file that is larger than 2 gigabyes.
Closes #1451 
```
/mnt/SDCARD/Roms/PS # du -h "Final Fantasy VIII.pbp"
2.1G    Final Fantasy VIII.pbp
```
> Fix games larger than 2GB not showing in GameSwitcher

- .gitignore
- Makefile
- src/pippi/Makefile
- src/pippi/pippi.c
- src/tree/Makefile
- src/tree/tree.c
- static/build/.tmp_update/script/network/update_networking.sh
Add `tree` command, that can take in optional arguments to exclude directories or to include extensions.
`Usage: %s <directory> [-e "directory_name1 directory_name2 ..."] [-i "ext1 ext2 ..."]`
e.g.
`tree /mnt/SDCARD/Roms/GB/ -e Imgs -i "7z zip gb"`
Add `pippi` command, takes in data from stdin and prints it's FNV1A_Pippip_Yurii hash to stdout
```
/ # echo "Hello World" | pippi
4046137546
/ # cat /mnt/SDCARD/.tmp_update/runtime.sh | pippi
1734444258
/ #
```
> Add tree and pippi

- src/common/theme/sound.h
Use the same algorithm to calculate the volume as MainUI
`(x << 7) / 20` is equivalent to `(x * 128) / 20` which is just plain linear scaling
Comparison:
Fixes #1046
> Fix discrepancy between MainUI and Onion volume

- src/batmon/batmon.c
- src/common/system/display.h
- src/keymon/keymon.c
This commit fixes a small bug where, if the user took a screenshot with low battery, the low battery icon would be showing in the screenshot.
To fix this, we do the following:
- We have the low battery thread check the raw display value and only draw if the raw value is not zero
- During the screenshot action, we reset the display to flush the battery icon out
- We wait a little bit to ensure our display is fresh before screenshotting
Since the display rawValue gets reset once the screenshot ends, the icon returns after the screenshot is done.
Issue describing the bug found here: https://github.com/OnionUI/Onion/issues/1504
> Hide low battery status during screenshot

- static/packages/RApp/PICO-8 (PICO-8 standalone)/RApp/PICO-8/cfg/onioncfg.json
Mouse can be tested in this cart (which is also available through splore):
https://www.lexaloffle.com/bbs/?tid=3467
- Fixes menu button handling so it doesn't exit on "PRESSED" event (fixes being unable to screenshot, change brightness etc) (may take 2 presses)
- Fixes mouse bounds from previous regression in #1425 
- Adds option flags to onioncfg.json to:
- Hide the mouse icon
- Set custom mouse bounds in the config (mostly for testing purposes)
- Remove the mouse hotkey altogether so it can be rebound to something else
These values will default to:
```c
#define MMIYOO_DEFAULT_MOUSE_HOTKEY         0
#define MMIYOO_DEFAULT_MOUSE_ICON           0
#define MMIYOO_DEFAULT_MOUSE_MINX           40
#define MMIYOO_DEFAULT_MOUSE_MINY           0
#define MMIYOO_DEFAULT_MOUSE_MAXX           280 …
```
> PICO-8 Standalone - Mouse/Menu key Improvements and fixes in SDL2 lib

- static/build/.tmp_update/script/netplay/easy-netplay_server.sh
EN is failing to launch RetroArch as it retrieves the wrong path from GLO. 
```
[INFO] [Content]: Loading content file: "/mnt/SDCARD/Emu/GB/launch.sh:/mnt/SDCARD/Emu/GB/../../Roms/GB/Balloon Kid (USA, Europe).zip".
[ERROR] [Content]: Could not read content file "/mnt/SDCARD/Emu/GB/launch.sh:/mnt/SDCARD/Emu/GB/../../Roms/GB/Balloon Kid (USA, Europe).zip"
```
This PR will fix the path passed into RetroArch and resolves: #1461 pending validation on review.
To reproduce:
Follow the instructions in the Issue, to reiterate:
- Launch Search, 
- Search for a netplay capable Rom (Balloon kid is a good choice)
- Open GLO
- Open Netplay, start Easy Netplay (Hotspot)
- Observe instant failure
Add script and re-follow instructions, now working.
> Fix Easy Netplay when starting through Search

- static/build/.tmp_update/runtime.sh
This adds the ability to always set the volume to a specific value during startup. It is enabled by writing the numeric value to `${sysdir}/config/.defaultVolume-${device_uuid}`. 
Ex.
```
$ cat .tmp_update/config/.defaultVolume-C2A037C6B080
7
$ cat .tmp_update/config/.defaultVolume-D7C3FDF55222
0
```
I developed this feature to solve different problems with both of my devices:
- **MMv4**: the runtime.sh script currently forces non-plus devices to maximum volume due to the device having an analog adjustment wheel ([see here](https://github.com/OnionUI/Onion/blob/61ff355a525c07dd024b0afcd3bfa7c43239b1ca/static/build/.tmp_update/runtime.sh#L725-L740)). However, this results in my device being _slightly_ audible even when the potentiometer is at its lowest. This is likely an issue with my …
>  Add feature to always set specific audio volume upon startup 

- src/keymon/keymon.c
- static/build/.tmp_update/runtime.sh
Keymon would force shutdown 30s after pressing the power button, and this would interrupt any scripts running during shutdown. This changes the keymon logic to skip the force shutdown, if the device is already in the process of shutting down.
> Skip keymon's force shutdown if runtime is already shutting down

- src/keymon/menuButtonAction.h
- static/packages/Emu/Nintendo - DS (Drastic)/Emu/NDS/launch.sh
This fixes a bug described below. This is due to the keymon assuming the exit button combo is MENU+L1, which is not the case when we swap L triggers. This commit now checks the JSON first, and swaps the exit button accordingly. 
1. Open NDS Game
2. Press MENU + START to open Drastic Settings Menu
3. Scroll down and toggle "Swap L1-L2" to "Yes"
4. Press B to return to Game
5. Press Menu
- Pressing MENU should exit the game
- Pressing MENU Loads State
> FIX: Setting Swap L1<>L2 in Drastic breaks Menu Exits

- static/build/.tmp_update/script/scraper/scrap_launchbox.sh
- static/build/.tmp_update/script/scraper/scrap_retroarch.sh
- static/build/.tmp_update/script/scraper/scrap_screenscraper.sh
Fixes #1636
Fix for the problem with square brackets in rom names not being escaped in the scraper scripts that caused `find` not finding the rom.
> Fix for scraper script character escaping

- src/common/system/lang.h
- src/common/system/settings.h
- src/common/theme/config.h
- src/common/utils/apply_icons.h
- src/common/utils/json.h
- src/gameSwitcher/gameSwitcher.c
- src/infoPanel/infoPanel.c
- src/randomGamePicker/randomGamePicker.c
- src/tweaks/icons.h
`cJSON` structures need to be deleted rather than free-ed so all sub-structures are cleaned up.
I don't think this was causing any major leaks but should now be causing no leaks :D.
See: https://github.com/OnionUI/Onion/blob/7dfc008b851398dcfe57819519efe5f958c77f65/include/cjson/cJSON.h#L146
> Fix memory leaks with cJSON

- src/batmon/batmon.c
When the battery db saturates, `log_new_percentage` will leak the drop statement each call.
> Fix memory leak in batmon

- src/clock/Makefile
- src/clock/main.c
No need to redraw if there has not been any events. Poll for events about every 100 ms. Drops utilization from around 25% to less than 0.
Also swap `-ffunction-sections -fdata-sections` for LTO to save ~5 Kb of memory when loaded and probably an immeasurable amount of performance.
Below is the size difference using LTO:
Addresses part of issue: https://github.com/OnionUI/Onion/issues/107
> Fix `clock` CPU utilization

- src/keymon/menuButtonAction.h
- src/tweaks/formatters.h
- src/tweaks/menus.h
- Add option in Tweaks:
- In-game: Menu button - ... < Quick menu >
- Toggles RetroArch's quick menu
- Use UDP protocol to exit RetroArch
- Fixes issues with exiting from arcade games
Test patch available here: [Onion_v4.3.1-1__menu_button_UDP_actions.zip](https://github.com/user-attachments/files/15973842/Onion_v4.3.1-1__menu_button_UDP_actions.zip)
> New in-game menu button action: "Quick menu" + fix quitting RetroArch from arcade games

- src/bootScreen/bootScreen.c
- src/common/components/JsonGameEntry.h
- src/common/system/lang.h
- src/common/system/screenshot.h
- src/common/system/settings.h
- src/common/system/state.h
- src/common/theme/config.h
- src/common/utils/apply_icons.h
- src/common/utils/file.c
- src/common/utils/file.h
- src/common/utils/json.h
- src/gameSwitcher/gameSwitcher.c
- src/infoPanel/infoPanel.c
- src/playActivity/cacheDB.h
- src/playActivity/migrateDB.h
- src/playActivity/playActivityDB.h
- src/randomGamePicker/randomGamePicker.c
- src/renameRom/renameRom.c
- src/tweaks/icons.h
Because `file_read` allocates memory, it should be free-ed. Currently,
attempting to do so will cause a compiler warning since `free` does
not take `const` qualified pointer (because we are modifying the
memory).
Changing the return type to `char *` rather than `const char *` will
allow the caller to correctly free memory.
Also fix most of the transitive leaks I could find. e.x. `strdup` returns allocated memory that should be free-ed.
Last patch doesn't really fix anything but adds the `malloc` function attribute for the compiler but also to hint to developers that the function allocates memory that needs to be free-ed.
> Common `file.c` util leaks

- src/common/system/settings.h
- src/keymon/keymon.c
- src/tweaks/menus.h
- static/build/.tmp_update/runtime.sh
- static/build/.tmp_update/script/blue_light.sh
- website/docs/07-apps/01-included-in-onion/blue-light-filter.md
- Enables the blue light schedule to work for the new Miyoo Mini V4 with RTC (or earlier revisions that have been modded).
- Prevent the blue light filter from always starting enabled on boot when the schedule says it should be off.
- Removed the network requirement, instead opting to blindly follow the current clock time if schedule is enabled.
> Enable blue light schedule to work for Miyoo Minis with RTC

- static/build/.tmp_update/runtime.sh
- website/docs/07-apps/01-included-in-onion/clock.md
Since the newest hardware revisions of the Miyoo Mini+ have RTC, it should be handled accordingly.
Detects if RTC is present, and does not restore and/or advance time if it is.
Works with newest Miyoo Mini+ with built in RTC as well as modded in RTC.
Edit: will also work on MM with RTC, see #1673
> Implement RTC detection for devices that have it (newer MM+)

- src/batmon/batmon.c
- src/batmon/batmon.h
- src/common/system/display.h
This PR fixes the following issues on the Miyoo Mini:
- Fixes sudden low battery warnings or shutdowns do to unstable/unsmoothed voltage reading
- Fixes inaccurate battery readings
- Fixes inaccurate voltage droop curve
- Prevent battery rising again due to system power draw changes. (about 80mv variance, a single percent on the battery)
- Fixes device not cutting of for 40 minutes to 1hr after hitting 0% battery
The existing issue was due to reading ADC value as if it was 4.3V to 3.3V.
The correct range should be from 4.2V to 3.0V as the miyoomini has a li-ion, not a li-po battery.
Additionally I havee simplified the ADC to voltage reading, and interpolated the voltage across a lookup table to make the battery percentage relation completly linear.
I also collected 10 samples of the …
> Fixed miyoo mini inaccurate battery readings.

- Makefile
- src/common/commands.mk
- src/common/recipes.mk
Use `make asan` either in root to compile everything or in an app directory to compile that app with address sanitizer enabled.
> Add make targets with enabled address sanitizer

- src/keymon/keymon.c
- static/packages/App/Music Player (GMU)/App/Gmu/launch.sh
GMU will now keep playing music when the screen is off. And the system-wide sleep timer will be disabled when using GMU.
- Added `stay_awake` flag when launching GMU
- Changed `keymon` to not suspend and mute when `stay_awake` is enabled
Closes #1717
> GMU: Keep the music playing when turning off display

- src/common/system/display.h
- src/common/system/state.h
- src/common/system/system_utils.h
- src/keymon/keymon.c
- src/keymon/menuButtonAction.h
- static/build/.tmp_update/runtime.sh
- static/build/.tmp_update/script/game_list_options.sh
With this feature, you can enjoy the seamless game transitions provided by GameSwitcher even if you have disabled the "auto load state" option in RetroArch. This means you can switch between games effortlessly without being forced to enable the auto load state feature in RetroArch.
- Disable the "auto load state" feature in RetroArch if you prefer not to use it.
- The auto save is not loaded when launching a game from the game list, search, or favorites.
- The auto save will still be loaded when you launch from GameSwitcher.
- Note: Quick switching will not create an auto save state.
> GameSwitcher: Seamless State Management

- src/keymon/keymon.c
- src/tweaks/actions.h
- src/tweaks/menus.h
- Add a toggle in **Tweaks -> Advanced** for enabling the global OC hotkeys (<kbd>SELECT</kbd>+<kbd>START</kbd>+<kbd>L</kbd>/<kbd>R</kbd>)
- Adjusted the max CPU from `1700/1900` to `1600/1800` due to user feedback (safe values)
> Tweaks: Add toggle for the new OC hotkeys

- static/configs/Saves/CurrentProfile/config/gpSP/gpSP.cfg
Avoid an extraneous blank line when configuration directives are appended by scripts.
> Remove empty line from gpSP.cfg

- website/docs/04-emulators/03-handhelds/02-bandai-wonderswan.md
The 'Bandai - WonderSwan / Color' page is missing the ``.wsc`` extension, which the emulator is able to play.
> Add .wsc to the Bandai WonderSwan docs page
